export const mockData: object[] = [
  {
    promotionId: 119,
    createdBy: "Ashleigh.Stafford@rclfoods.com",
    eventName: "SPAR JAN SPREADS WCAPE PROMO",
    majorGroup: null,
    majorChain: null,
    subChain: null,
    promotionStatusId: 0,
    promotionStatusName: "Planned",
    customerType: null,
    custRegion: null,
    custName: null,
    category: null,
    subCategory: null,
    brand: null,
    packSizeName: null,
    productName: null,
    businessUnit: null,
    titan: null,
    multiBuy: false,
    comments: null,
    year: 2021,
    month: "Jan",
    tbc: false,
    createdDate: "11 Nov 2020",
    startDate: "25 Jan 2021",
    endDate: "07 Feb 2021",
    fiscalYear: "F21",
    marginSupport: false,
    marginSupportAmount: null,
    marginSupportPromotionSpendType: null,
    sally: false,
    sallyAmount: null,
    sallyPromotionSpendType: null,
    tally: false,
    tallyAmount: null,
    tallyPromotionSpendType: null,
    rsp: false,
    rspPromotionSpendType: null,
  },
  {
    promotionId: 122,
    createdBy: "Ashleigh.Stafford@rclfoods.com",
    eventName: "SPAR ECAPE SPREADS PROMO",
    majorGroup: null,
    majorChain: null,
    subChain: null,
    promotionStatusId: 0,
    promotionStatusName: "Planned",
    customerType: null,
    custRegion: null,
    custName: null,
    category: null,
    subCategory: null,
    brand: null,
    packSizeName: null,
    productName: null,
    businessUnit: null,
    titan: null,
    multiBuy: false,
    comments: null,
    year: 2021,
    month: "Jan",
    tbc: false,
    createdDate: "11 Nov 2020",
    startDate: "25 Jan 2021",
    endDate: "07 Feb 2021",
    fiscalYear: "F21",
    marginSupport: false,
    marginSupportAmount: null,
    marginSupportPromotionSpendType: null,
    sally: false,
    sallyAmount: null,
    sallyPromotionSpendType: null,
    tally: false,
    tallyAmount: null,
    tallyPromotionSpendType: null,
    rsp: false,
    rspPromotionSpendType: null,
  },
  {
    promotionId: 307,
    createdBy: "Ashleigh.Stafford@rclfoods.com",
    eventName: "Spar Ecape Grocery Promo",
    majorGroup: null,
    majorChain: null,
    subChain: null,
    promotionStatusId: 0,
    promotionStatusName: "Planned",
    customerType: null,
    custRegion: null,
    custName: null,
    category: null,
    subCategory: null,
    brand: null,
    packSizeName: null,
    productName: null,
    businessUnit: null,
    titan: null,
    multiBuy: false,
    comments: null,
    year: 2021,
    month: "Jan",
    tbc: false,
    createdDate: "17 Nov 2020",
    startDate: "11 Jan 2021",
    endDate: "24 Jan 2021",
    fiscalYear: "F21",
    marginSupport: false,
    marginSupportAmount: null,
    marginSupportPromotionSpendType: null,
    sally: false,
    sallyAmount: null,
    sallyPromotionSpendType: null,
    tally: false,
    tallyAmount: null,
    tallyPromotionSpendType: null,
    rsp: false,
    rspPromotionSpendType: null,
  },
  {
    promotionId: 317,
    createdBy: "Ashleigh.Stafford@rclfoods.com",
    eventName: "Spar Inland Grocery Promo",
    majorGroup: null,
    majorChain: null,
    subChain: null,
    promotionStatusId: 0,
    promotionStatusName: "Planned",
    customerType: null,
    custRegion: null,
    custName: null,
    category: null,
    subCategory: null,
    brand: null,
    packSizeName: null,
    productName: null,
    businessUnit: null,
    titan: null,
    multiBuy: false,
    comments: null,
    year: 2021,
    month: "Jan",
    tbc: false,
    createdDate: "17 Nov 2020",
    startDate: "11 Jan 2021",
    endDate: "24 Jan 2021",
    fiscalYear: "F21",
    marginSupport: false,
    marginSupportAmount: null,
    marginSupportPromotionSpendType: null,
    sally: false,
    sallyAmount: null,
    sallyPromotionSpendType: null,
    tally: false,
    tallyAmount: null,
    tallyPromotionSpendType: null,
    rsp: false,
    rspPromotionSpendType: null,
  },
  {
    promotionId: 74,
    createdBy: "Chanel.Naidoo@rclfoods.com",
    eventName: "MAKRO MORE FOR LESS M4L Q1 2021",
    majorGroup: null,
    majorChain: null,
    subChain: null,
    promotionStatusId: 0,
    promotionStatusName: "Confirmed",
    customerType: null,
    custRegion: null,
    custName: null,
    category: null,
    subCategory: null,
    brand: null,
    packSizeName: null,
    productName: null,
    businessUnit: null,
    titan: null,
    multiBuy: false,
    comments: null,
    year: 2021,
    month: "Jan",
    tbc: false,
    createdDate: "10 Nov 2020",
    startDate: "01 Jan 2021",
    endDate: "31 Mar 2021",
    fiscalYear: "F21",
    marginSupport: false,
    marginSupportAmount: null,
    marginSupportPromotionSpendType: null,
    sally: false,
    sallyAmount: null,
    sallyPromotionSpendType: null,
    tally: false,
    tallyAmount: null,
    tallyPromotionSpendType: null,
    rsp: false,
    rspPromotionSpendType: null,
  },
  {
    promotionId: 79,
    createdBy: "Rosheal.Dhanookdhari@rclfoods.com",
    eventName: "MAKRO MORE FOR LESS",
    majorGroup: null,
    majorChain: null,
    subChain: null,
    promotionStatusId: 0,
    promotionStatusName: "Confirmed",
    customerType: null,
    custRegion: null,
    custName: null,
    category: null,
    subCategory: null,
    brand: null,
    packSizeName: null,
    productName: null,
    businessUnit: null,
    titan: null,
    multiBuy: false,
    comments: null,
    year: 2021,
    month: "Jan",
    tbc: false,
    createdDate: "10 Nov 2020",
    startDate: "01 Jan 2021",
    endDate: "31 Mar 2021",
    fiscalYear: "F21",
    marginSupport: false,
    marginSupportAmount: null,
    marginSupportPromotionSpendType: null,
    sally: false,
    sallyAmount: null,
    sallyPromotionSpendType: null,
    tally: false,
    tallyAmount: null,
    tallyPromotionSpendType: null,
    rsp: false,
    rspPromotionSpendType: null,
  },
  {
    promotionId: 192,
    createdBy: "Ashleigh.Stafford@rclfoods.com",
    eventName: "SPAR KZN CHICKEN PROMO FTF & DRUMS",
    majorGroup: null,
    majorChain: null,
    subChain: null,
    promotionStatusId: 0,
    promotionStatusName: "Planned",
    customerType: null,
    custRegion: null,
    custName: null,
    category: null,
    subCategory: null,
    brand: null,
    packSizeName: null,
    productName: null,
    businessUnit: null,
    titan: null,
    multiBuy: false,
    comments: null,
    year: 2020,
    month: "Dec",
    tbc: false,
    createdDate: "13 Nov 2020",
    startDate: "29 Dec 2020",
    endDate: "10 Jan 2021",
    fiscalYear: "F21",
    marginSupport: false,
    marginSupportAmount: null,
    marginSupportPromotionSpendType: null,
    sally: false,
    sallyAmount: null,
    sallyPromotionSpendType: null,
    tally: false,
    tallyAmount: null,
    tallyPromotionSpendType: null,
    rsp: false,
    rspPromotionSpendType: null,
  },
  {
    promotionId: 493,
    createdBy: "Lisa.Pillay@rclfoods.com",
    eventName: "Dec Month End Ouma Rusk 450gr Broadsheet ",
    majorGroup: null,
    majorChain: null,
    subChain: null,
    promotionStatusId: 0,
    promotionStatusName: "Confirmed",
    customerType: null,
    custRegion: null,
    custName: null,
    category: null,
    subCategory: null,
    brand: null,
    packSizeName: null,
    productName: null,
    businessUnit: null,
    titan: null,
    multiBuy: false,
    comments: null,
    year: 2020,
    month: "Dec",
    tbc: false,
    createdDate: "19 Nov 2020",
    startDate: "28 Dec 2020",
    endDate: "03 Jan 2021",
    fiscalYear: "F21",
    marginSupport: false,
    marginSupportAmount: null,
    marginSupportPromotionSpendType: null,
    sally: false,
    sallyAmount: null,
    sallyPromotionSpendType: null,
    tally: false,
    tallyAmount: null,
    tallyPromotionSpendType: null,
    rsp: false,
    rspPromotionSpendType: null,
  },
  {
    promotionId: 494,
    createdBy: "Lisa.Pillay@rclfoods.com",
    eventName: "Dec Month End Ouma Rusk 500gr Broadsheet ",
    majorGroup: null,
    majorChain: null,
    subChain: null,
    promotionStatusId: 0,
    promotionStatusName: "Confirmed",
    customerType: null,
    custRegion: null,
    custName: null,
    category: null,
    subCategory: null,
    brand: null,
    packSizeName: null,
    productName: null,
    businessUnit: null,
    titan: null,
    multiBuy: false,
    comments: null,
    year: 2020,
    month: "Dec",
    tbc: false,
    createdDate: "19 Nov 2020",
    startDate: "28 Dec 2020",
    endDate: "03 Jan 2021",
    fiscalYear: "F21",
    marginSupport: false,
    marginSupportAmount: null,
    marginSupportPromotionSpendType: null,
    sally: false,
    sallyAmount: null,
    sallyPromotionSpendType: null,
    tally: false,
    tallyAmount: null,
    tallyPromotionSpendType: null,
    rsp: false,
    rspPromotionSpendType: null,
  },
  {
    promotionId: 495,
    createdBy: "Lisa.Pillay@rclfoods.com",
    eventName: "Dec Month End Nola 500gr Core National Broadsheet",
    majorGroup: null,
    majorChain: null,
    subChain: null,
    promotionStatusId: 0,
    promotionStatusName: "Confirmed",
    customerType: null,
    custRegion: null,
    custName: null,
    category: null,
    subCategory: null,
    brand: null,
    packSizeName: null,
    productName: null,
    businessUnit: null,
    titan: null,
    multiBuy: false,
    comments: null,
    year: 2020,
    month: "Dec",
    tbc: false,
    createdDate: "19 Nov 2020",
    startDate: "28 Dec 2020",
    endDate: "03 Jan 2021",
    fiscalYear: "F21",
    marginSupport: false,
    marginSupportAmount: null,
    marginSupportPromotionSpendType: null,
    sally: false,
    sallyAmount: null,
    sallyPromotionSpendType: null,
    tally: false,
    tallyAmount: null,
    tallyPromotionSpendType: null,
    rsp: false,
    rspPromotionSpendType: null,
  },
];
